apiVersion: v1
kind: Service
metadata:
  name: rpg-music
  namespace: rpg-music
  labels:
    app: rpg-music-streaming
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: rpg-music-streaming
  sessionAffinity: ClientIP  # Important for WebSocket connections
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
